#!/usr/bin/env bash

# First make sure no tests have been edited
if git rev-parse --quiet --verify HEAD > /dev/null
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=ffe715aeabeab24a32639cfe95da1c4e2a0da576
fi

ERRORS="false"

# Get list of files changed
FILE_LIST=`git diff-index --diff-filter=AM --name-only --cached $against

for file in $FILE_LIST
do
    # make sure file is in onboardtests directory
    if ! `echo $file | grep "onboardtests" >/dev/null 2>&1` ; then
      ERRORS="true"
      echo "Error: Changing test files (${file}) is not a good way to pass tests!"
    fi
done

if [ "$ERRORS" == "true" ] ; then
   exit 1
fi

set -e
export CFLAGS=-Qunused-arguments
export CPPFLAGS=-Qunused-arguments

curdir=$(dirname $0)
cd $curdir/../../
PS1=''
VENV='/usr/bin/virtualenv-2.7'
${VENV} . && source bin/activate
# shitty shim for Mac OS X El Capitan
# SIP (https://developer.apple.com/library/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_11.html#//apple_ref/doc/uid/TP40016227-DontLinkElementID_19)
# prevents modifying things like /usr/include so we have to tell pip where to find sasl.h
if [ $(command -v xcrun) ] 
then
	export CFLAGS="${CFLAGS} -I$(xcrun --show-sdk-path)/usr/include/sasl"
fi
pip install --upgrade setuptools
pip install -r requirements-dev.txt
python run_tests.py
